# Generated by Django 4.1 on 2022-09-13 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_currency_alter_invoice_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='EOB', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='invoices.paymentterms'),
            preserve_default=False,
        ),
    ]
