# Generated by Django 4.1 on 2022-09-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_paymentterms_invoice_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterms',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
