# Generated by Django 4.1 on 2022-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_paymentterms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterms',
            name='name',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
