# Generated by Django 4.1 on 2022-09-13 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_paymentterms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.paymentterms'),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='name',
            field=models.TextField(max_length=10),
        ),
    ]
