# Generated by Django 4.1 on 2022-09-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_payment_terms_alter_paymentterms_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_terms',
        ),
    ]
