# Generated by Django 4.1 on 2022-09-13 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_remove_invoice_payment_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTerms',
        ),
    ]
