# Generated by Django 4.1 on 2022-09-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_delete_paymentterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[(1, 'EOB'), (2, 'EOM')], default='EOB', max_length=20),
        ),
    ]
