# Generated by Django 4.1 on 2022-09-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=100)),
                ('country', models.TextField(max_length=100)),
            ],
        ),
    ]
